apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: satishpri001/account-service:latest
        resources:
          limits:
              memory: "500Mi"
              cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 9292
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://account-db-service:5432/account-db"

        - name: SPRING_DATASOURCE_USERNAME
          value: "user"

        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"

---

apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: LoadBalancer
  selector:
    app: account-service
  ports:
  - port: 80
    targetPort: 9292
