spring.application.name=payment-service
server.port=9999
server.servlet.context-path=/txn

#H2 DATABASE CONFIGURATION
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#H2 DATABSE FORMATTING
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#DEBUG
debug=true

#LOGGING
file.logs

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1


# Default retry config
resilience4j.retry.configs.default.max-attempts=3
resilience4j.retry.configs.default.waitDuration=5s

# Instance-specific config
resilience4j.retry.instances.paymentRetry.baseConfig=default
resilience4j.retry.instances.paymentRetry.waitDuration=200ms

resilience4j.ratelimiter.instances.paymentRateLimiter.limitRefreshPeriod=5s
resilience4j.ratelimiter.instances.paymentRateLimiter.limitForPeriod=1
resilience4j.ratelimiter.instances.paymentRateLimiter.timeoutDuration=1s

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.waitDurationInOpenState=1s
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.eventConsumerBufferSize=10