spring.application.name=api-gateway-service
server.port=9494
#server.servlet.context-path=/api

# Route for user-service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**
#spring.cloud.gateway.server.webflux.routes[0].filters[0]=RedirectTo=302, http://youtube.com
spring.cloud.gateway.server.webflux.routes[0].filters[0]=AddRequestHeader=x-custome-header,satish

# Route for account-service
spring.cloud.gateway.server.webflux.routes[1].id=account-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/accounts/**

# Route for payment-service
spring.cloud.gateway.server.webflux.routes[2].id=payment-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/txn/**

debug=true


#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
